# Generated by Django 6.0.3 on 2026-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
